# Generated by Django 3.2.5 on 2021-08-02 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='updates_at',
            new_name='updated_at',
        ),
    ]
