# Generated by Django 3.2.5 on 2021-08-02 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_users_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email_address',
            new_name='email',
        ),
    ]
