# Generated by Django 3.2.5 on 2021-08-02 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_rename_email_address_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Apple', max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('op_sys', models.CharField(default='macOS 12.0', max_length=250)),
                ('cpu', models.CharField(max_length=150)),
                ('memory', models.IntegerField()),
                ('mem_type', models.BooleanField(default=False)),
                ('storage', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='users_app.users')),
            ],
        ),
    ]
